### ISSUE TITLE
Modal Backdrop (nearly) never fits

### ISSUE THREAD

**Issue by DaSchTour** [twbs/bootstrap#15136]
Because of the change with modal backdrop and the new function from #15106 there are a lot of problems with the modal backdrop now.
1. It's a major break in backward compatibility. I have to rewrite the complete handling of modals to ensure that with every action inside the modal the backdrop is updated
2. Even bootstraps own functions don't use the modal handling. So with every collapsable panel inside a modal I will have problems with the backdrop.
3. Why the hell was this changed in 3.3.0? From my point of view the modals worked perfectly before 3.3.0!
4. Is there any solution to attach a "size changes" handler to the modal that updates the modal without having to manually call the the update handler?

**Comment by DaSchTour** [comment]
3 months between 3.3.1 and 3.3.2? So when this is in 3.3.4 I'll have to wait another 6 months for this crucial fix? Why can't we get the old version back that worked a lot better than the current solution? If there is no solution coming I'll have just ad a timer that resizes the backdrop every second while a modal is open. At this point I'm really disappointed of this project. Including such a big break in backward compatibility and not being able to fix such a big issue makes me think, that this project will not work as nice as it did in the future, so for my next project I'll check for other frameworks.

**Comment by fahdoo** [comment]
Agreed. Upgrading to new versions is blocked for us till this is fixed since we use modals in key features

**Comment by j3l11234** [comment]
╮(╯_╰)╭ Agreed

**Comment by RomeroMsk** [comment]
Agreed :+1:

**Comment by sdalezman** [comment]
@hnrch02 I agree to the `position: fixed;` + padding fix, but I am pretty sure most browsers hide the scroll bar if you aren't currently scrolling by default (chrome, safari, ff on mac osx). On Safari in osx if you switch back to position fixed though the scroll bar doesn't appear even when a user scrolls. So not really sure it's a viable solution because then [#14916](https://github.com/twbs/bootstrap/issues/14916) is reintroduced as a usability problem in safari. 

Another solution might be to dynamically check the height of the modal after it is show and compare the modal inner + outer height to the window height, if the modal inner + outer is greater apply the padding to take into account the scroll bar. However, I am not sure if the code maintenance on something so minor is really worth it and it wouldn't solve the problem on safari. 

@DaSchTour  if you want to go back to the way it was before just add to your css:
``` css
.modal-backdrop {
  position: fixed;
  bottom: 0;
  height: auto !important; \\ to override bootstrap defined height which won't take into account dynamic height
}
```

**Comment by DaSchTour** [comment]
@sdalezman you missed the top:0 that is important to have a height!

**Comment by LeEnno** [comment]
@DaSchTour if you're actually *adding* the css, you just need these three lines, since `top: 0` is already set in https://github.com/twbs/bootstrap/blob/master/less/modals.less#L66

I still think manually updating the height via`handleUpdate()` is not the best solution. What's wrong with the combination of #15314 and [eliminating all calls to `adjustBackdrop()`](https://github.com/twbs/bootstrap/pull/15314/files#r21586977)?

**Comment by DaSchTour** [comment]
@LeEnno I see. I thought that the snippet should be a replacement for the current .modal-backdrop
BTW: I change it to use width: 100% instead of left:0 and right:0. Is there a difference? Might this also be a possible change to resolve conflicts with scrollbars?

**Comment by cvrebert** [comment]
@hnrch02 Any update on this? This issue is attracting a lot of duplicates.

**Comment by 4Digits** [comment]
Is there any progress on this issue?

I am using a form with dynamic form validation within the modal. If the height of the modal changes after its initial creation, it always pushes out of the background (.modal-backdrop) depending on screen size. 

I tried 

```
.modal-backdrop {
  position: fixed;
  top: 0;
  bottom: 0;
  height: auto !important; 
}
```
but it is not a great solution regarding usability as you can now only scroll the modal to see the full content. 

Isn't there a way to dynamically adjust the height of `.modal-backdrop` when the modal content changes?

**Comment by nickalbrecht** [comment]
Until a solution is found that provides as much coverage as possible, the above mentioned call to ```handleUpdate``` works for me. I'm not using the collapse component however, but instead loading the contents of the dialog manually via AJAX. I was able to apply this fix by incorporating it into my complete callback using something analogous to the below
```
$(".modal-body").load("[url]", {someData: "something"}, function(){ $(".modal").modal("handleUpdate"); })
```
Alternatively, the native ```remote``` option fires a ```loaded.bs.modal``` event when the load completes as well.

As for the root issue, since both the dialog and the native collapse behavior are a part of the same framework, why not have the modal dialog monitor for ```shown.bs.collapse``` events, and call the ```handleUpdate``` method? Something analogous of...
```
$(".modal").on("shown.bs.collapse", function (e) {$(e.delegateTarget).modal("handleUpdate")})
```

**Comment by DaSchTour** [comment]
That would only be a partial solution for me, as we don't use the remote option as it doesn't work as we need it. We also change the modal content while the modal is open and all these function now would need to handle the size change of the modal.

**Comment by 4Digits** [comment]
Making a manual AJAX call to get a simple modal working is a bit overkill, I think...

**Comment by DaSchTour** [comment]
@4Digits that's nothing of an overkill. Just fill the modal content through ajax and than call the modal open. It's very easy and you need only need one modal dummy in the page. I don't know what should be overkill here? All other solutions I tried to get to work with our AJAX SPRING Solution didn't work out.

**Comment by nickalbrecht** [comment]
Well I say manually, I mean using the jquery load method. The reason I use that over the built in remote functionality is I need to rip out the header and footer elements from the result and place them in the header, or wire up new buttons in the footer (to preserve form functionality). I've got it all wired up to anchor tags if they have a special data attribute present, to load the href in a modal instead of navigating in the browser. There really isn't a better way when you're customizing the header, body, and footer of the dialog.

If your modal content is changed inconsistently or not through a central method, then yeah, you'd end up with calls to that ```handleUpdate``` method all over. Mine were all done through one reusable javascript call that I could add it to one or two places and I'm done. If you can't explicitly call a method when you alter the contents of the dialog, the only other solution that I can think of is to basically have something watch the contents of the modal (which I'm guessing is what MutationObserver would accomplish), and adjust (call that handleUpdate method) the modal dialog accordingly. Might be a little much to incorporate into Bootstrap, but it may solve your problem if you have no other options. The only other option would be to find a way to revise modal dialogs so that sizing of the backdrop to no longer be sensitive to added content which enlarges the height of the dialog beyond that of the current viewport in an already visible modal.

**Comment by DaSchTour** [comment]
We need to fix this!!! As I was working on other parts of my WebApp I discovered that the solution by @4Digits doesn't work correctly in Google Chrome. Neither height: auto nor height:100% work correctly in Google Chrome. So please please please finally fix this issue and release a new version, I don't like to be punched by this issue every week.

**Comment by hnrch02** [comment]
I opened a PR with a potential fix for this at #15881.

**Comment by cvrebert** [comment]
Please direct any further feedback on this to #15881 or file new issues.
