### ISSUE TITLE
Carousel Responsive Issue In Chrome

### ISSUE THREAD

**Issue by benjaminthedev** [twbs/bootstrap#21966]
Hello there, 

I have created a Carousel and when responsive in Chrome it squashes the image rather than scale down. Does anyone else have this issue? This is happening on all my desktop devices in Chrome. 

Here is an image to highlight it.

http://imgur.com/a/5lOr8

This is also happening on BS4 doc Carousel page:

https://v4-alpha.getbootstrap.com/components/carousel/#options

Cheers

**Comment by josmaissan** [comment]
Same as #21611 I think.

**Comment by benjaminthedev** [comment]
Yes thanks it is and you have helped me. Thanks so much. This should be fixed tho right??

**Comment by josmaissan** [comment]
> This should be fixed tho right??

I hope they fixe. In my opinion they should, but it's not added to milestone v4.0.0-beta yet...
I have just added an example on JSFiddle too, in case they want that.

**Comment by benjaminthedev** [comment]
Wicked, yeah they should at some point do that. What is the link to the fiddle if you do not mind me asking? Cheers.

**Comment by josmaissan** [comment]
It's in my last post at #21611 ofcourse, but is: https://jsfiddle.net/josmaissan/5jsonocq/15/

**Comment by kwhdever** [comment]
24 Feb 17
Confirm the carousel "image squashing" is still an issue, on Chrome Version 56.0.2924.87 (Windows 7)
Carousel worked fine in A5.

To demo:
1) Go to URL:
https://v4-alpha.getbootstrap.com/components/carousel/
2) Narrow the viewport
3) Observe the image crush. Images do not resize.

**Comment by josmaissan** [comment]
@kwhdever Your right! #21611 is still open. 😉
