### ISSUE TITLE
input[type=date] with empty value shrunken height on mobile

### ISSUE THREAD

**Issue by rixlabs** [twbs/bootstrap#23307]
On iPad, an input of type date that doesn't have any initial value appear smaller until touched or a date selected.

I tested the same situation on Chrome for Android and there is working fine

Reduced test case here: [http://jsfiddle.net/ctesyxxx/1/](http://jsfiddle.net/ctesyxxx/1/)
Tested on: Safari for iPad , iOS 10.1.1

**Comment by ianbrandt** [comment]
@rixlabs Same here.  Did you find a workaround by chance?

**Comment by rixlabs** [comment]
@ianbrandt I did exactly the same...

**Comment by ianbrandt** [comment]
Updated my workaround to also account for https://github.com/twbs/bootstrap/issues/18842:

```
input[type="text"],
input[type="email"],
input[type="date"] {
	height: 2.375rem;
}
```

So far tested on Safari and Chrome on iOS and macOS, and Edge on Windows 10.

(In case it's not obvious you'll want to add any other input types you use, e.g. "password", "url", etc.)

**Comment by jckh1234** [comment]
I found it not only shorten the but also move the input slightly lower when placing inside a div.

https://stackoverflow.com/questions/49932842/html5-input-type-date-not-vertical-align-property-in-mobile-browser-when-value-i

**Comment by parisiam** [comment]
I encountered exactly the same problem in ios 11 and bootstrap 4.1.2: the temporal fields shrink if no initial value is selected.
[https://jsfiddle.net/parisiam/0teuo9dy/50/](https://jsfiddle.net/parisiam/0teuo9dy/50/)
Another solution is to combine the field inside an input group with an icon (a calendar for instance). 
![capture d ecran 2018-07-14 a 15 38 51](https://user-images.githubusercontent.com/627813/42724958-3985577e-877c-11e8-8c5b-66f4a07ea4a5.png)

**Comment by pekanct** [comment]
My solution was:
```
<input type="text "placeholder="Select a date" onfocus="$(this).hide().next().attr('hidden',false).focus();"/>
<input type="datetime-local"  hidden="true">
```

**Comment by mdo** [comment]
This should’ve been solved in v4.1.3 when we added fixed heights to inputs.

**Comment by floppyTop** [comment]
@mdo , I see that the fixed height has been added and so that fixes the collapsing issue.. quick question though. Are you aware of any way to prevent the hidden value issue? Although the height is no longer collapsed, I am unable to see a pre-populated value on an input[type="date"] unless I first focus on it, then the value does show.

**Comment by rixlabs** [comment]
I've tested again with the last version and it is indeed fixed! 

Check here : http://jsfiddle.net/7fxdt260/

Tested on: Safari for iPad , iOS 10.1.1

**Comment by hotsoft-desenv2** [comment]
@mdo I think it's not solved yet... I'm using the latest version but the problem still present....

**Comment by karlbeecken** [comment]
I still have the problem, but this works for me:
`<input type="text "placeholder="Select a date onfocus="$(this).hide().next().attr('hidden',false).focus();"/>
<input type="datetime-local"  hidden="true">`

**Comment by mdo** [comment]
@MartijnCuppens @ysds #28917 mentions the fixed height change, but I didn't see that in the diff. Bad cross-reference, or something I'm missing?

**Comment by MartijnCuppens** [comment]
This demo is an example of `v4-alpha`, this seems to be fixed in the meantime:

Before:
![image](https://user-images.githubusercontent.com/11559216/73681343-704c4a80-46be-11ea-9cbe-469bf089f6b9.png)

After:
![image](https://user-images.githubusercontent.com/11559216/73681364-7b06df80-46be-11ea-9f98-4f260155cbc2.png)

**Comment by winner** [comment]
> My solution was:
> 
> ```
> <input type="text "placeholder="Select a date" onfocus="$(this).hide().next().attr('hidden',false).focus();"/>
> <input type="datetime-local"  hidden="true">
> ```

Thanks very much!!!
