### ISSUE TITLE
tables inside of columns in IE11 not stacking as expected at small size

### ISSUE THREAD

**Issue by ccartee** [twbs/bootstrap#25358]
https://jsfiddle.net/charleycartee/s7ze7r5b/

load in ie
shrink window/pane size size.  Tables will overlap
repeat in edge/chrome; note tables stack instead of overlapping

When reporting a bug, include:

- Windows 10, ie11

**Comment by ccartee** [comment]
actually, I see the same sort of overlap in chrome with col-3 (instead of col)

https://jsfiddle.net/charleycartee/s7ze7r5b/3/

There's still some sort of inconsistancy (where the first example stacks in chrome and edge, but not in ie11), but I'm no longer convinced that I'm sure which should be the expected behavior.

**Comment by Johann-S** [comment]
we released a few hours ago our first stable and before that we were at beta 3, your JSFiddle use our Beta 1.

Please update your JSFiddle

**Comment by tomalakgeretkal** [comment]
@Johann-S getbootstrap.com still says current version is v4.0.0-beta.3

**Comment by ccartee** [comment]
I think I grabbed the right urls
beta 3: https://jsfiddle.net/charleycartee/s7ze7r5b/11/ (happens in IE and chrome with this one)
release: https://jsfiddle.net/charleycartee/s7ze7r5b/12/ (happens in ie with this one)
release: https://jsfiddle.net/charleycartee/s7ze7r5b/13/ (happens in ie and chrome with this one)


same behavior in ie

**Comment by ccartee** [comment]
incidently: https://getbootstrap.com/ still shows beta 3 as current.

**Comment by tomalakgeretkal** [comment]
@ccartee I found that yesterday as well, but then it changed almost immediately. I think there's some dodgy caching going on; try a hard refresh or otherwise wait. It does show 4.0.0 for me now.

**Comment by ccartee** [comment]
I reloaded again (not a hard refresh) and it's showing as 4.0.0 now

**Comment by ccartee** [comment]
fiddle was updated 6 days ago.  Issue is still there in the release version.  This is still marked "awaiting reply"

**Comment by ccartee** [comment]
uh, it totally does the same thing with col-sm-3

https://jsfiddle.net/charleycartee/km2o9g1y/

**Comment by ccartee** [comment]
or this one:

https://jsfiddle.net/charleycartee/bfd20nz3/
